# Generated by Django 2.2 on 2019-10-26 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Extend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorite',
            field=models.CharField(default='None', max_length=10),
        ),
    ]
